#!/usr/bin/env python3
"""Compiles the presenter's post-processing shaders to SPIR-V and writes post_spirv.h.

Run after editing a shader (needs glslc, e.g. `brew install shaderc`); the header is committed so
builds don't need a shader compiler.
"""
import pathlib
import subprocess
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
SHADERS = ["fullscreen.vert", "fxaa.frag", "fsr_easu.frag", "fsr_rcas.frag", "smaa_edges.frag", "smaa_weights.frag",
           "smaa_blend.frag", "depth_view.frag", "motion_view.frag", "taa.frag", "depth_normalize.frag", "ui_composite.frag", "frame_gen.frag", "copy.frag", "flicker.frag", "flicker_cut.frag", "flicker_grid.frag", "flicker_weight.frag"]

out = ["#pragma once", "", "// Generated by compile.py from the shaders in this directory. Do not edit.", "",
       "#include <cstdint>", "", "namespace ps2x::gs::post_spirv", "{"]
with tempfile.TemporaryDirectory() as tmp:
    for name in SHADERS:
        spv = pathlib.Path(tmp) / (name + ".spv")
        subprocess.run(["glslc", "-O", "--target-env=vulkan1.1", "-I", str(HERE), str(HERE / name), "-o", str(spv)],
                       check=True)
        data = spv.read_bytes()
        words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
        ident = name.replace(".", "_")
        out.append(f"    inline constexpr uint32_t {ident}[] = {{")
        for i in range(0, len(words), 8):
            out.append("        " + ", ".join(f"0x{w:08x}" for w in words[i:i + 8]) + ",")
        out.append("    };")
out.append("}")
(HERE / "post_spirv.h").write_text("\n".join(out) + "\n")
print("wrote", HERE / "post_spirv.h")
